name: New Project Proposal
description: This form is for new software projects that like to join HPSF.
title: "[Project Proposal]: "
labels: ["Project Proposal"]
body:
  - type: input
    id: project-name
    attributes:
      label: 1. Name of Project
    validations:
      required: true

  - type: textarea
    id: project-description
    attributes:
      label: 2. Project Description
    validations:
      required: true

  - type: textarea
    id: mission-alignment
    attributes:
      label: 3. Statement on Alignment with High Performance Software Foundation's Mission
    validations:
      required: true

  - type: input
    id: project-website
    attributes:
      label: 4. Project Website
      description: Please provide a link to the project website.
      placeholder: https://www.yoursite.org
    validations:
      required: false

  - type: textarea
    id: open-source-license
    attributes:
      label: 5. Open Source License
      description: |
        Please provide your license information. 
        - [SPDX Identifier](https://spdx.org/licenses/)
        - If the project also ships data artifacts, what Open Access licenses are used?
    validations:
      required: true

  - type: input
    id: code-of-conduct
    attributes:
      label: 6. Code of Conduct
      description: Please provide a link to your Code of Conduct.
      placeholder: https://www.codeofconduct.org
    validations:
      required: false

  - type: input
    id: governance-practices
    attributes:
      label: 7. Governance Practices
      description: Please provide a link to your project governance documentation.
      placeholder: https://www.projectgovernance.org
    validations:
      required: false

  - type: textarea
    id: tac-sponsors
    attributes:
      label: 8. Two Sponsors from the High Performance Software Foundation's Technical Advisory Committee
    validations:
      required: true

  - type: input
    id: source-control
    attributes:
      label: 9. What is the project's solution for source control?
    validations:
      required: true

  - type: input
    id: issue-tracking
    attributes:
      label: 10. What is the project's solution for issue tracking?
    validations:
      required: true

  - type: textarea
    id: external-dependencies
    attributes:
      label: 11. Please list all external dependencies and their license
    validations:
      required: true

  - type: textarea
    id: release-methodology
    attributes:
      label: 12. Please describe your release methodology and mechanics
    validations:
      required: true

  - type: textarea
    id: software-quality
    attributes:
      label: 13. Please describe Software Quality efforts (CI, security, auditing)
    validations:
      required: true

  - type: textarea
    id: leadership-team
    attributes:
      label: 14. Please list the project's leadership team
    validations:
      required: true

  - type: textarea
    id: mainline-committers
    attributes:
      label: 15. Please list the project members with access to commit to the mainline of the project
    validations:
      required: true

  - type: textarea
    id: decision-making
    attributes:
      label: 16. Please describe the project's decision-making process
    validations:
      required: true

  - type: dropdown
    id: maturity-level
    attributes:
      label: 17. What maturity level of your project?
      options:
        - Emerging
        - Established
        - Core
    validations:
      required: true

  - type: textarea
    id: communication-channels
    attributes:
      label: 18. Please list the project's official communication channels
    validations:
      required: false

  - type: textarea
    id: social-media
    attributes:
      label: 19. Please list the project's social media accounts
    validations:
      required: false

  - type: textarea
    id: financial-sponsorships
    attributes:
      label: 20. Please describe any existing financial sponsorships
    validations:
      required: false

  - type: textarea
    id: infrastructure-needs
    attributes:
      label: 21. Please describe the project's infrastructure needs or requests
    validations:
      required: false