name: "Project Review: Core Stage"
description: "Requested Stage: Core"
title: "[Project Review: Core Stage]: "
labels: ["Project Review"]
body:
  - type: markdown
    attributes:
      value: |
        Projects shall be reviewed by a three-member committee of TAC voting members appointed by the TAC Chair.
        See [IV. Periodic Review Process](https://github.com/hpsfoundation/tac/blob/main/lifecycle_policy.md#iv-periodic-review-process).

  - type: input
    id: project-name
    attributes:
      label: 1. Name of Project
    validations:
      required: true
      
  - type: input
    id: project-proposal
    attributes:
      label: 2. Project Proposal
      description: Please provide a link to the project proposal and the last project review, if any.
      placeholder: https://github.com/hpsfoundation/tac/issues/
    validations:
      required: true

  - type: textarea
    id: project-description
    attributes:
      label: 3. Project Description
    validations:
      required: true
      
  - type: input
    id: project-website
    attributes:
      label: 4. Project Website
      description: Please provide a link to the project website.
      placeholder: https://www.yoursite.org
    validations:
      required: false
      
  - type: textarea
    id: open-source-license
    attributes:
      label: 5. Open Source License
      description: |
        Please provide your license information. 
        - [SPDX Identifier](https://spdx.org/licenses/)
        - If the project also ships data artifacts, what Open Access licenses are used?
      value: No changes since the project proposal or last review.
    validations:
      required: true
      
  - type: input
    id: code-of-conduct
    attributes:
      label: 6. Code of Conduct
      description: Please provide a link to your Code of Conduct.
      placeholder: https://www.codeofconduct.org
      value: No changes since the project proposal or last review.
    validations:
      required: false

  - type: input
    id: governance-practices
    attributes:
      label: 7. Governance Practices
      description: Please provide a link to your project governance documentation.
      placeholder: https://www.projectgovernance.org
      value: No changes since the project proposal or last review.
    validations:
      required: false
      
  - type: input
    id: source-control
    attributes:
      label: 8. What is the solution for source control?
      value: No changes since the project proposal or last review.
    validations:
      required: true
      
  - type: input
    id: issue-tracking
    attributes:
      label: 9. What is the solution for issue tracking?
      value: No changes since the project proposal or last review.
    validations:
      required: true
      
  - type: textarea
    id: external-dependencies
    attributes:
      label: 10. Please list all external dependencies and their license
      value: No changes since the project proposal or last review.
    validations:
      required: true
      
  - type: textarea
    id: release-methodology
    attributes:
      label: 11. Please describe your release methodology and mechanics
      value: No changes since the project proposal or last review.
    validations:
      required: true
      
  - type: textarea
    id: software-quality
    attributes:
      label: 12. Please describe Software Quality efforts (CI, security, auditing)
      value: No changes since the project proposal or last review.
    validations:
      required: true
      
  - type: textarea
    id: leadership-team
    attributes:
      label: 13. Please list the leadership team
      value: No changes since the project proposal or last review.
    validations:
      required: true
      
  - type: textarea
    id: mainline-committers
    attributes:
      label: 14. Please list the project members with access to commit to the mainline of the project
      value: No changes since the project proposal or last review.
    validations:
      required: true
      
  - type: textarea
    id: decision-making
    attributes:
      label: 15. Please describe the decision-making process
      value: No changes since the project proposal or last review.
    validations:
      required: true
    
  - type: dropdown
    id: current-stage
    attributes:
      label: 16. Current Stage
      options:
        - Emerging
        - Established
        - Core
    validations:
      required: true

  - type: dropdown
    id: requested-stage
    attributes:
      label: 17. Requested Stage
      description: |
        Projects or a TAC Voting Member may also request a review at any time to present a case to move to a new stage.
        Projects may also request reassignment to an earlier stage at the time of their review.
        See [IV. Periodic Review Process](https://github.com/hpsfoundation/tac/blob/main/lifecycle_policy.md#iv-periodic-review-process).
      options:
        - Core
      default: 0
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ### [Emerging Projects](https://github.com/hpsfoundation/tac/blob/main/lifecycle_policy.md#emerging-projects)
        To be considered for the Emerging Stage, the project must meet the following requirements:

  - type: textarea
    id: criterion-emerging-mission
    attributes:
      label: "18. Emerging Stage: Align with the mission of the HPSF as laid out above. This will be determined by a majority vote of the TAC"
    validations:
      required: true

  - type: textarea
    id: criterion-emerging-governance
    attributes:
      label: "19. Emerging Stage: Have a publicly available governance document — even if your governance is somewhat ad hoc, state what it is, including the project's technical leadership and roles"
    validations:
      required: true

  - type: textarea
    id: criterion-emerging-status
    attributes:
      label: "20. Emerging Stage: Upon acceptance, projects must list their status prominently on their website/README"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ### [Established Stage](https://github.com/hpsfoundation/tac/blob/main/lifecycle_policy.md#established-stage)
        To be considered for Established Stage, the project must meet the Emerging requirements as well as the following:

  - type: textarea
    id: criterion-established-production-use
    attributes:
      label: "21. Established Stage: Document that it is being used successfully in production by at least three independent end users which, in the TAC’s judgment, are of adequate quality and scope."
    validations:
      required: true

  - type: textarea
    id: criterion-established-development-processes
    attributes:
      label: "22. Established Stage: Demonstrate development processes (e.g., use of pull requests, code review, testing, CI) that lower barriers to contribution and ensure software quality necessary for increased adoption."
    validations:
      required: true

  - type: textarea
    id: criterion-established-contribution-flow
    attributes:
      label: "23. Established Stage: Demonstrate a substantial ongoing flow of commits and merged contributions."
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        Since these metrics can vary significantly depending on the type, scope and size of a project, the TAC has final judgment over the level of activity that is adequate to meet these criteria.

  - type: markdown
    attributes:
      value: |
        ### [Core Stage](https://github.com/hpsfoundation/tac/blob/main/lifecycle_policy.md#core-stage)
        Projects can move directly from Emerging to Core, if they can demonstrate sufficient maturity and have met all requirements.

        To graduate from Emerging or Established status, or for a new project to join as a Core project, a project must meet the Established stage criteria plus:

  - type: textarea
    id: criterion-core-governing-body
    attributes:
      label: "24. Core Stage: Have a defined governing body of at least 4 or more members (owners and core maintainers), of which no more than 1/2 of whom are affiliated with the same employer. No single institution may control a voting majority of the governing body."
    validations:
      required: true

  - type: textarea
    id: criterion-core-governance-documentation
    attributes:
      label: "25. Core Stage: Have a documented and publicly accessible description of the project's governance, decision-making, and release processes."
    validations:
      required: true

  - type: textarea
    id: criterion-core-committers
    attributes:
      label: "26. Core Stage: Have a healthy number of committers from at least two organizations. A committer is defined as someone with the commit bit; i.e., someone who can accept contributions to some or all of the project."
    validations:
      required: true

  - type: textarea
    id: criterion-core-security
    attributes:
      label: "27. Core Stage: Explicitly defined security reporting and incident mitigation processes, as appropriate to the security risks of the project"
    validations:
      required: true

  - type: textarea
    id: criterion-core-governance-committer-process
    attributes:
      label: "28. Core Stage: Explicitly defined project governance and committer process."
    validations:
      required: true

  - type: textarea
    id: criterion-core-adoption
    attributes:
      label: "29. Core Stage: Provide evidence of widespread adoption in the HPC ecosystem or in some important component thereof."
    validations:
      required: true

  - type: textarea
    id: presentation
    attributes:
      label: 30. Presentation
      description: Optional, you can link slides here.
    validations:
      required: false

  - type: textarea
    id: communication-channels
    attributes:
      label: 31. Please list the project's official communication channels
      value: No changes since the project proposal or last review.
    validations:
      required: false

  - type: textarea
    id: social-media
    attributes:
      label: 32. Please list the project's social media accounts
      value: No changes since the project proposal or last review.
    validations:
      required: false

  - type: textarea
    id: financial-sponsorships
    attributes:
      label: 33. Please describe any existing financial sponsorships
      value: No changes since the project proposal or last review.
    validations:
      required: false

  - type: textarea
    id: infrastructure-needs
    attributes:
      label: 34. Please describe the project's infrastructure needs or requests
      value: No changes since the project proposal or last review.
    validations:
      required: false
